### ISSUE TITLE
swscale-5.dll not found in release version

### ISSUE THREAD

**Issue by Musickiller** [SuperSpaceEye/TheLifeEngineCpp#54]
Hi! As you can guess from the header, I'm unable to launch the release version, beause some lib, swscale-5 is not found in my system.

Do you know what's that?)

Kind Regards,
Dima

**Comment by SuperSpaceEye** [comment]
Updated the latest release version. Please check now

**Comment by SuperSpaceEye** [comment]
i'll close it for now. reopen if it didn't work

**Comment by Musickiller** [comment]
Hi! Sorry for the delay((

Now it says Application Error 0xc000007b, but the previous error is gone. Should I create a new issue for that?)

For some reason I seem to be unable to reopen the issue o_O

**Comment by Musickiller** [comment]
@SuperSpaceEye same happens in older version when I copy the DLL in question there.

**Comment by SuperSpaceEye** [comment]
I've updated release again (i basically chuked almost every dll from my dev env lol) and if it still doesn't work, pls screenshot

**Comment by SuperSpaceEye** [comment]
well, i'll close it again for now

**Comment by Musickiller** [comment]
yep, it works, thanks!
