### ISSUE TITLE
Zooms out very fast

### ISSUE THREAD

**Issue by BoKa33** [SuperSpaceEye/TheLifeEngineCpp#55]
The programm is very sensitiv to using the mousewheel on the canvas, so it often accidently happens that you scroll out way to fast. Then the programm crashes very early.

**Comment by SuperSpaceEye** [comment]
huh, it indeed does crash if you zoom out too much

**Comment by SuperSpaceEye** [comment]
btw you can set "Scaling coefficient" in settings to make zoom less powerful

**Comment by SuperSpaceEye** [comment]
anyways, it will be fixed in the next update (if it even releases). But for now just try to not zoom out too much i guess?
