### ISSUE TITLE
Crash without error messages

### ISSUE THREAD

**Issue by Musickiller** [SuperSpaceEye/TheLifeEngineCpp#56]
Hi, it's me again!))

I've got crash to desktop on last release version. No error messages, almost no freeze, just a crash.

Where can I find logs, if there are any?

**Comment by SuperSpaceEye** [comment]
Well, for performance reasons there are no checks anywhere. And for lazy reasons I haven't written tests for anything. So if it crashes it means that it is probably a segfault which shouldn't happen but it did somehow

**Comment by SuperSpaceEye** [comment]
Honestly, the code became an unmaintainable mess so random crashes are sadly expected. I want to eventually write a more proper version from scratch, but i don't really have time or energy for it.

**Comment by SuperSpaceEye** [comment]
I think saving/loading worlds have some sort of memory leak or smth that introduces instability, as if you just play without using it it never crashed for me. But still, there could be some sort of bug that causes this, but it would be probably easier to rewrite everything than try to find and fix the problem.
