### ISSUE TITLE
Web - Windows save version (possible) incompatability

### ISSUE THREAD

**Issue by Musickiller** [SuperSpaceEye/TheLifeEngineCpp#57]
When I load a save from web version of LEE into my Windows version, all organisms are dead. And it also takes all my RAM to load the simulation. It's not small, but I don't get any of these issues on the web version.

Here's the save: https://pixeldrain.com/u/47su9fGc

**Comment by SuperSpaceEye** [comment]
damn i compiled a version from dev branch, not from master one

**Comment by SuperSpaceEye** [comment]
i think

**Comment by SuperSpaceEye** [comment]
hmmm no that's not it

**Comment by SuperSpaceEye** [comment]
it works sometimes for me so idk
