### ISSUE TITLE
[Suggestion] More mover blocks increase speed (Option)

### ISSUE THREAD

**Issue by lupuleasa-core** [SuperSpaceEye/TheLifeEngineCpp#58]
Hi,

I am absolutely loving this, and I can help implement this if needed in a PR

But currently, I want to suggest this and also ask: Does this already exist?

From Emergent Garden's video I instantly found it strange that "more movement blocks does not do anything" rule, does not seem intuitive

The way I was thinking of implementation is increasing max move distance based on move blocks.
I know it is just teleportation, but still. Consider it "jumping"

**Comment by SuperSpaceEye** [comment]
With continuous movement enabled the amount of movers matters, but i don't really remember how it worked anymore.
