### ISSUE TITLE
Some option explanations miss from "Info" page

### ISSUE THREAD

**Issue by lupuleasa-core** [SuperSpaceEye/TheLifeEngineCpp#59]
I noticed some of these are missing, they seem cool but I can't figure out what they do to play with them

![image](https://github.com/SuperSpaceEye/LifeEngineExtended/assets/5671120/075a46d6-3303-4dcb-8454-6bc672c270a4)

Also, related suggestion, does the UI frontend support tooltips? Having a tooltip on hover like the original lifeengine would do wonders

**Comment by SuperSpaceEye** [comment]
With continuous movement only weighted brain is available. Also, i'm no longer working on it.
